# Compilers

c_compiler:
  - clang                         # [osx]
  - gcc                           # [linux]
cxx_compiler:
  - clangxx                       # [osx]
  - gxx                           # [linux]
fortran_compiler:
  - gfortran
target_platform:
  - osx-64                        # [osx]
  - linux-64                      # [linux]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk           # [osx]

# Packages
blas:
  - 2.17
cmake:
  - 3.18.0
intel_openmp:
  - 2020.0
mkl_static:
  - 2020.0
mkl_include:
  - 2020.0
llvm_openmp:
  - 10.0.1
numpy:
  - 1.18
openmp:
  - 8.0.1
python:
  - 3.6
  - 3.7
  - 3.8

pin_run_as_build:
  blas:
    max_pin: x.x
  intel_openmp:
    max_pin: x
  mkl_static:
    max_pin: x
  mkl_include:
    max_pin: x
  llvm_openmp:
    max_pin: x.x
  openmp:
    max_pin: x.x
