{% set name = "cint" %}
{% set version = "3.0.17" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/GQCG/libcint.git
    git_tag: develop
requirements:
    build:
      - cmake {{ cmake }}
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - git
      - make
    host:
      - blas {{ blas }}
      - intel-openmp {{ intel_openmp }}
      - llvm-openmp                    # [osx]
      - mkl-static {{ mkl_static }}
      - mkl-include {{ mkl_include }}
      - numpy
      - openmp {{ openmp }}            # [linux]
      - python
    run:
      - blas
      - intel-openmp      
      - llvm-openmp                    # [osx]
      - numpy
      - openmp                         # [linux]
      - python

test:
  commands:
    - test -f ${PREFIX}/lib/libcint$SHLIB_EXT
    - test -f ${PREFIX}/include/cint.h
    - ldd -v ${PREFIX}/lib/libcint$SHLIB_EXT    # [linux]
    - otool -L ${PREFIX}/lib/libcint$SHLIB_EXT  # [osx]
about:
    home: https://github.com/GQCG/libcint
    license: BSD
    license_file: LICENSE
    summary: 'General GTO integrals for quantum chemistry.'
