name: Build and test

on: pull_request

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        py: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
      - name: Python ${{ matrix.py }} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.py }}
      - name: Install conda dependencies 
        run: |
          conda install -c conda-forge cmake=3.18 blas=2.17 mkl=2020.0 numpy=1.19
          conda install -c intel mkl-static=2020.0 mkl-include=2020.0 intel-openmp=2020.0
      - name: Build, test and install
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=${HOME}/miniconda -DUSE_MKL=TRUE -DENABLE_TEST=1
          make -j2 VERBOSE=1 && env CTEST_OUTPUT_ON_FAILURE=1 make test && sudo make install
