name: Conda CI

on:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
      - name: Python ${{ matrix.python-version }} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, intel
      - name: Download MacOSX 10.9 SDK as conda-build dependency
        if: matrix.os == 'macos-latest'
        run: |
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz
          sudo mkdir /opt/MacOSX10.9.sdk
          sudo tar -xf MacOSX10.9.sdk.tar.xz -C /opt
          ls -hal /opt/MacOSX10.9.sdk
      - name: Deploy conda package
        run: |
          conda create -n packaging -c conda-forge conda-build anaconda-client conda-verify
          source activate packaging
          conda config --set anaconda_upload no
          conda-build -c conda-forge -c intel conda --user ${{ secrets.ANACONDA_USER }} --token ${{ secrets.ANACONDA_TOKEN }} --variants "{python: [${{ matrix.py }}] }"
          anaconda logout
