name: Conda CI

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        py: [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
      - name: Python ${{ matrix.py }} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.py }}
          conda-channels: anaconda, conda-forge, intel
      - name: Download MacOSX 10.9 SDK as conda-build dependency
        if: matrix.os == 'macos-10.15'
        run: |
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz
          sudo mkdir /opt/MacOSX10.9.sdk
          sudo tar -xf MacOSX10.9.sdk.tar.xz -C /opt
          ls -hal /opt/MacOSX10.9.sdk
      - name: Deploy conda package
        run: |
          conda create -n packaging python=${{ matrix.py }}
          source activate packaging
          conda install -c conda-forge conda-build anaconda-client conda-verify --freeze-installed
          conda config --set anaconda_upload no
          conda-build -c conda-forge -c intel conda --user ${{ secrets.ANACONDA_USER }} --token ${{ secrets.ANACONDA_TOKEN }} --variants "{python: [${{ matrix.py }}] }"
          anaconda logout
